name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  docker:
    name: CI Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag icuadrosaforo255/node-devops:$GITHUB_RUN_NUMBER .
    - name: Login to Docker Hub
      run: docker login --username icuadrosaforo255 --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the docker image
      run: docker push icuadrosaforo255/node-devops:$GITHUB_RUN_NUMBER
  
  merge-branch:
    name: Merge to master
    needs: docker
    # needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}