name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag icuadrosaforo255/node-devops:$GITHUB_RUN_NUMBER .
    - name: Login to Docker Hub
      run: docker login --username icuadrosaforo255 --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the docker image
      run: docker push icuadrosaforo255/node-devops:$GITHUB_RUN_NUMBER
