# name: Pull Request
 
# on:
#   workflow_run:
#     workflows: [ "Docker Image CI" ]
#     types:
#       - completed
#   workflow_dispatch:
 
# jobs:
#   work:
#     name: Some Workflow Work
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Some work"

name: Pull Request
 
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed
  workflow_dispatch:
 
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.TOKEN_PR }}